server:
  port: 3000

spring:
  # 프로필 설정
  profiles:
    active: dev

  # 데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: PROJECT
    password: _aA123456

  # 파일 업로드 설정(들여쓰기 주의)
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 40MB

  # 정적 자원 설정(CSS, JS, 이미지)(서버 껐다켰다 안해도 될 수 있게)
  resources:
    staticLocations: file:src/main/resources/static/

  # 라이브 리로드 설정(나중에 꼭 꺼야됨 (서버부담))
  devtools:
    livereload:
      enable: true

  # 타임리프 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  # 입력한 sql 초기에 실행
  flyway:
    enable: true

file:
  upload:
    path: C:/uploads/
    url: /uploads/

# 로거 설정
logging:
  level:
    org:
      springframework:
        jdbc: trace